CREATE TABLE `analyses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`homeTeamId` int NOT NULL,
	`awayTeamId` int NOT NULL,
	`homeTeamName` varchar(255) NOT NULL,
	`awayTeamName` varchar(255) NOT NULL,
	`analysisMode` enum('mode1','mode2') NOT NULL DEFAULT 'mode2',
	`homeProjectedShots` decimal(10,2) NOT NULL,
	`awayProjectedShots` decimal(10,2) NOT NULL,
	`homeProjectedShotsOnTarget` decimal(10,2) NOT NULL,
	`awayProjectedShotsOnTarget` decimal(10,2) NOT NULL,
	`homeProjectedCorners` decimal(10,2) NOT NULL,
	`awayProjectedCorners` decimal(10,2) NOT NULL,
	`homeProjectedGoals` decimal(10,2) NOT NULL,
	`awayProjectedGoals` decimal(10,2) NOT NULL,
	`homeOffensiveConversion` decimal(10,4) NOT NULL,
	`homeDefensiveConversion` decimal(10,4) NOT NULL,
	`awayOffensiveConversion` decimal(10,4) NOT NULL,
	`awayDefensiveConversion` decimal(10,4) NOT NULL,
	`homePressureFactor` decimal(10,4) NOT NULL,
	`awayPressureFactor` decimal(10,4) NOT NULL,
	`projectedHomeGoals` int NOT NULL,
	`projectedAwayGoals` int NOT NULL,
	`rankingData` json NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `analyses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `teamStats` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`dangerousAttacksFor` decimal(10,2) NOT NULL,
	`dangerousAttacksAgainst` decimal(10,2) NOT NULL,
	`cornersFor` decimal(10,2) NOT NULL,
	`cornersAgainst` decimal(10,2) NOT NULL,
	`shotsFor` decimal(10,2) NOT NULL,
	`shotsAgainst` decimal(10,2) NOT NULL,
	`shotsOnTargetFor` decimal(10,2) NOT NULL,
	`shotsOnTargetAgainst` decimal(10,2) NOT NULL,
	`goalsFor` decimal(10,2) NOT NULL,
	`goalsAgainst` decimal(10,2) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `teamStats_id` PRIMARY KEY(`id`)
);
