CREATE TABLE `fixtures` (
	`id` int AUTO_INCREMENT NOT NULL,
	`apiFixtureId` int NOT NULL,
	`date` varchar(10) NOT NULL,
	`time` varchar(5) NOT NULL,
	`timezone` varchar(64) NOT NULL DEFAULT 'America/Sao_Paulo',
	`country` varchar(128) NOT NULL,
	`countryCode` varchar(8),
	`league` varchar(255) NOT NULL,
	`leagueId` int NOT NULL,
	`season` int,
	`round` varchar(128),
	`homeTeam` varchar(255) NOT NULL,
	`homeTeamId` int NOT NULL,
	`awayTeam` varchar(255) NOT NULL,
	`awayTeamId` int NOT NULL,
	`homeLogo` varchar(512),
	`awayLogo` varchar(512),
	`homeScore` int,
	`awayScore` int,
	`status` enum('scheduled','live','halftime','finished','postponed','cancelled','unknown') NOT NULL DEFAULT 'scheduled',
	`statusShort` varchar(10),
	`elapsed` int,
	`hasAnalysis` int NOT NULL DEFAULT 0,
	`analysisId` int,
	`userId` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fixtures_id` PRIMARY KEY(`id`)
);
