CREATE TABLE `dailyMatchQuality` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fixtureId` int NOT NULL,
	`matchDate` varchar(10) NOT NULL,
	`homeTeam` varchar(255) NOT NULL,
	`awayTeam` varchar(255) NOT NULL,
	`homeTeamId` int NOT NULL,
	`awayTeamId` int NOT NULL,
	`league` varchar(255) NOT NULL,
	`country` varchar(128) NOT NULL,
	`time` varchar(5),
	`qualityScore` decimal(4,2) NOT NULL,
	`qualityLabel` enum('excellent','good','acceptable','caution','avoid') NOT NULL,
	`dataAvailabilityScore` decimal(4,2) NOT NULL,
	`homeAwayScore` decimal(4,2) NOT NULL,
	`offensiveVolumeScore` decimal(4,2) NOT NULL,
	`defensiveVolumeScore` decimal(4,2) NOT NULL,
	`competitiveBalanceScore` decimal(4,2) NOT NULL,
	`contextRiskScore` decimal(4,2) NOT NULL,
	`bestBlocksJson` json NOT NULL,
	`alertsJson` json NOT NULL,
	`explanation` text,
	`projectedStatsJson` json,
	`sportmonksHomeTeamId` int,
	`sportmonksAwayTeamId` int,
	`sportmonksSeasonId` int,
	`userId` int NOT NULL,
	`calculatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `dailyMatchQuality_id` PRIMARY KEY(`id`)
);
