CREATE TABLE `accuracyRecords` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`analysisId` int NOT NULL,
	`fixtureId` int,
	`matchDate` varchar(10) NOT NULL,
	`homeTeamName` varchar(255) NOT NULL,
	`awayTeamName` varchar(255) NOT NULL,
	`league` varchar(255),
	`projectedHomeGoals` int NOT NULL,
	`projectedAwayGoals` int NOT NULL,
	`projectedHomeShots` decimal(6,2),
	`projectedAwayShots` decimal(6,2),
	`projectedHomeCorners` decimal(6,2),
	`projectedAwayCorners` decimal(6,2),
	`projectedHomeShotsOnTarget` decimal(6,2),
	`projectedAwayShotsOnTarget` decimal(6,2),
	`actualHomeGoals` int NOT NULL,
	`actualAwayGoals` int NOT NULL,
	`actualHomeShots` int,
	`actualAwayShots` int,
	`actualHomeCorners` int,
	`actualAwayCorners` int,
	`actualHomeShotsOnTarget` int,
	`actualAwayShotsOnTarget` int,
	`rankingLineResults` json NOT NULL,
	`totalLines` int NOT NULL DEFAULT 0,
	`greenCount` int NOT NULL DEFAULT 0,
	`yellowCount` int NOT NULL DEFAULT 0,
	`redCount` int NOT NULL DEFAULT 0,
	`hitRate` decimal(5,2) NOT NULL DEFAULT '0',
	`goalProjectionHit` int DEFAULT 0,
	`goalDiff` int,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `accuracyRecords_id` PRIMARY KEY(`id`)
);
